defmodule CodeseekerWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :codeseeker

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :codeseeker,
    gzip: not code_reloading?,
    only: CodeseekerWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library(),
    body_reader: {CodeseekerWeb.Plugs.RawBodyReader, :read_body, []}

  plug Plug.MethodOverride
  plug Plug.Head
  plug CodeseekerWeb.Router
end
